from constraint_satisfaction_problem.graph_coloring.generators.grid_generator import \
    generate_adjacency_matrix_graph_coloring
from constraint_satisfaction_problem.graph_coloring.generators.grid_generator import \
    generate_double_adjacency_matrix_graph_coloring
from constraint_satisfaction_problem.graph_coloring.generators.grid_generator import \
    generate_adjacency_matrix_latin_square
