from constraint_satisfaction_problem.graph_coloring.simulations.simulation import SimulationGraphColoring
from constraint_satisfaction_problem.graph_coloring.simulations.simulation import SimulationLatinSquare

